## Numpy

수치해석용 패키지 : 배열 데이터

In [0]:
import numpy as np

In [0]:
data = np.array([1, 2, 3, 4, 5, 6], dtype='f')
data

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [0]:
data.shape

(6,)

In [0]:
data.ndim

1

In [0]:
data.dtype

dtype('float32')

#### 배열 변환

In [0]:
#형변환
data.astype('i')

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [0]:
data.astype('O') #문자열

array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=object)

In [0]:
#shape변환
data.reshape([3, 2]) #3행 2열

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

#### 배열 생성

In [0]:
data = np.zeros([5, 2]) #0행렬
data

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
data = np.ones([10, ])
data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
data = np.array([i for i in range(10)])
data_zero = np.zeros_like(data) #data와 같은 shape의 0행렬
data_zero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
data_one = np.ones_like(data)
data_one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
data_empty = np.empty([3, 4])
data_empty

array([[2.50668830e-316, 0.00000000e+000, 4.27366784e-321,
        1.28037073e-316],
       [6.94628768e-310, 6.94628768e-310, 6.94628768e-310,
        6.94628768e-310],
       [2.50668830e-316, 1.48219694e-323, 1.90979621e-313,
        0.00000000e+000]])

In [0]:
data_arange = np.arange(1, 11) #1부터 10까지
data_arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
data_lin = np.linspace(1, 10, 10) # 1부터 10까지 10개
data_lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
data_log = np.logspace(1, 10, 10)
data_log

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [0]:
data_rand = np.random.rand(3, 2) #0~1
data_rand

array([[0.43884589, 0.95488024],
       [0.83410859, 0.80500566],
       [0.63443001, 0.24903464]])

In [0]:
data_randn = np.random.randn(2, 3) #E = 0, V = 1 
data_randn

array([[-0.65355166,  1.4877162 ,  0.07218716],
       [-2.14991769,  1.39570071,  1.53500126]])

In [0]:
data_randint = np.random.randint(1, 10, (4, 2)) #1부터 10사이의 숫자, (4행2열)
data_randint

array([[5, 8],
       [9, 1],
       [8, 8],
       [7, 6]])

#### 벡터화 연산

In [0]:
#리스트
data = [1, 2, 3]
data * 2

[1, 2, 3, 1, 2, 3]

In [0]:
#numpy => ndarray
data = np.array([1, 2, 3])
data*2

array([2, 4, 6])

In [0]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 0, 1])
arr1 * arr2 #[1*1, 2*0, 3*1]

array([1, 0, 3])

In [0]:
arr1@arr2 #내적곱 = 1*1 + 2*0 + 3*1

4

#### 배열 인덱싱

In [0]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[data%3==0]

array([3, 6, 9])

In [0]:
data_randn = np.random.randn(2, 3)
data_randn

array([[-0.32619815, -2.32675345, -0.02970727],
       [-0.60360438,  0.28739094,  0.969597  ]])

In [0]:
#Transpose
data_randn.T

array([[-0.32619815, -0.60360438],
       [-2.32675345,  0.28739094],
       [-0.02970727,  0.969597  ]])

In [0]:
# data_randn@data_randn
data_randn@data_randn.T

array([[ 5.52106937, -0.50059732],
       [-0.50059732,  1.38705015]])

In [0]:
data_randn.T@data_randn

array([[ 0.47074348,  0.58551223, -0.57556254],
       [ 0.58551223,  5.49637517,  0.3477749 ],
       [-0.57556254,  0.3477749 ,  0.94100087]])

In [0]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])