In [1]:
import tensorflow as tf
tf.__version__

'2.2.0'

# Tensorflow


TensorFlow vs PyTorch  
Google vs Facebook  

# Type

## constant

In [2]:
a = tf.constant(10)

In [4]:
b = tf.constant(5, dtype=tf.float32)
b

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [6]:
c = tf.constant([1, 2], dtype=tf.float32)
c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [8]:
d = tf.constant([[1,2], [3,4]], dtype=tf.float32)
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## Variable

In [9]:
v1 = tf.Variable(3, dtype=tf.float32)
v1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [11]:
v2 = tf.Variable([1,2 ], dtype=tf.float32)
v2

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

# rank, shape

In [14]:
a, b, c, d

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>)

In [17]:
tf.rank(a), tf.rank(b), tf.rank(c), tf.rank(d)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [18]:
a.shape, b.shape, c.shape, d.shape

(TensorShape([]), TensorShape([]), TensorShape([2]), TensorShape([2, 2]))

In [22]:
import numpy as np
e = np.arange(27)
e = e.reshape(3, 3, 3)

In [25]:
e = tf.constant(e)
e.shape

TensorShape([3, 3, 3])

In [28]:
tf.rank(e)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## Operator

In [33]:
a = tf.cast(a, tf.float32)
a

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [36]:
tf.add(a, b), a + b

(<tf.Tensor: shape=(), dtype=float32, numpy=15.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=15.0>)

In [37]:
tf.multiply(a, b)

<tf.Tensor: shape=(), dtype=float32, numpy=50.0>

## cast

In [41]:
arr1 = np.arange(10.0)
arr1.dtype

dtype('float64')

In [43]:
arr1 = arr1.astype(np.int64)
arr1.dtype

dtype('int64')

In [44]:
a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [47]:
tf.cast(a, tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=10.0>

## Sequence Data

In [52]:
tf.range(1.0, 10.0, 1)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [55]:
tf.linspace(1.0, 12.0, 10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.       ,  2.2222223,  3.4444444,  4.6666665,  5.888889 ,
        7.111111 ,  8.333333 ,  9.555555 , 10.777778 , 12.       ],
      dtype=float32)>

In [57]:
tf.zeros((3, 3), dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [58]:
tf.ones((3, 3), dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [61]:
e.shape

TensorShape([3, 3, 3])

In [62]:
tf.ones_like(e, dtype=tf.float32)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [64]:
tf.zeros_like(e, dtype=tf.float32)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

## reduce_*

In [67]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=351>

In [69]:
tf.reduce_prod(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [70]:
e.shape

TensorShape([3, 3, 3])

In [72]:
e

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [71]:
tf.reduce_sum(e, axis=0)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])>

In [74]:
tf.reduce_sum(e, axis=1)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])>

In [76]:
tf.reduce_sum(e, axis=2)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])>

## random

In [84]:
a = tf.random.normal((3,3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.25452837, -1.1043092 ,  0.8459585 ],
       [-0.78182656,  0.67386353, -2.440698  ],
       [-1.0921378 , -0.51685095, -0.51219374]], dtype=float32)>

In [83]:
tf.random.uniform((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6272538 , 0.12373352, 0.07958984],
       [0.3921163 , 0.5531001 , 0.88862777],
       [0.5131383 , 0.5172479 , 0.04411161]], dtype=float32)>

## math

In [86]:
tf.math.abs(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.25452837, 1.1043092 , 0.8459585 ],
       [0.78182656, 0.67386353, 2.440698  ],
       [1.0921378 , 0.51685095, 0.51219374]], dtype=float32)>

In [87]:
tf.math.sqrt(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[      nan,       nan, 0.91976  ],
       [      nan, 0.8208919,       nan],
       [      nan,       nan,       nan]], dtype=float32)>