# 파이썬 라이브러리를 활용한 머신러닝_사이킷런
##### _한빛미디어

## sickit-learn
- NumPy, SciPy, pandas, matplotlib etc.

# NumPy
- 파이썬으로 과학 계산
- 다차원 배열을 위한 선형 대수 연산, 푸리에 변환 등 고수준 수학 함수 + 유사 난수 생성기 포함! 
- sikit-learn에서 NumPy는 기본 데이터 구조; NumPy 형태의 데이터를 입력으로 받음.
- 다차원 배열인 ndarray 클래스가 핵심 기능! (모든 원소는 동일한 데이터 타입이어야 한다.)

In [8]:
# NumPy 배열의 예

import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n", x)

x:
 [[1 2 3]
 [4 5 6]]


In [9]:
# SciPy

from scipy import sparse

eye = np.eye(4)
print("NumPy 배열: \n", eye)

NumPy 배열: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy의 CSR 행렬:\n", sparse_matrix)


SciPy의 CSR 행렬:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [13]:
# 희소 행렬 직접 만들기
# 희소 행렬 (Sparse matrix): 행렬 대부분의 값이 0으로 이루어진 것

data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))

print("COO 표현:\n", eye_coo)

COO 표현:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
